//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WookieBooks.Utility.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class wb_resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal wb_resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WookieBooks.Utility.Properties.wb-resource", typeof(wb_resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Save Error.
        /// </summary>
        public static string WB001 {
            get {
                return ResourceManager.GetString("WB001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Delete Error.
        /// </summary>
        public static string WB002 {
            get {
                return ResourceManager.GetString("WB002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Books Retrieve Error.
        /// </summary>
        public static string WB003 {
            get {
                return ResourceManager.GetString("WB003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Retrieve Error.
        /// </summary>
        public static string WB004 {
            get {
                return ResourceManager.GetString("WB004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Update Error.
        /// </summary>
        public static string WB005 {
            get {
                return ResourceManager.GetString("WB005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Fill Required Data.
        /// </summary>
        public static string WB006 {
            get {
                return ResourceManager.GetString("WB006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occurred.
        /// </summary>
        public static string WB007 {
            get {
                return ResourceManager.GetString("WB007", resourceCulture);
            }
        }
    }
}
